export const PREDEFINED_RESPONSES = {
    "aku lagi sedih banget hari ini.": "Aku dengerin kok. Sedih itu wajar banget, jangan dipendam sendirian ya. Mau cerita lebih lanjut?",
    "asli, aku bingung mau mulai tugas dari mana.": "Pasti pusing ya kalau semuanya numpuk. Coba tarik napas dulu, kita urutkan satu-satu yuk.",
    "kuliah hari ini bosan banget, pengen balik.": "Haha, emang ada masanya kuliah berasa flat banget. Semangat ya, dikit lagi kelar kok!",
    "aku cuma merasa sedikit lelah aja sih.": "Gak apa-apa capek sedikit. Istirahat sejenak itu investasi buat energi kamu nanti.",
    "kenapa ya aku begini terus setiap malam?": "Pertanyaan itu sering muncul saat kita lagi lelah mental. Kamu gak sendirian ngerasain itu.",
    "senang sih lulus ujian, tapi capek banget.": "Selamat ya! Tapi wajar banget kalau fisiknya tetep kerasa gempor. Bobo manis dulu gih!",
    "hidupku gitu-gitu aja, kuliah pulang kuliah pulang.": "Rutinitas kadang emang bikin jenuh. Mungkin nanti sore bisa coba jalan cari angin sebentar?",
    "lagi mager parah, gak mau ngapa-ngapain.": "Nikmatin aja magernya sebentar, anggap aja lagi 'recharging' baterai diri.",
    "perasaanku hari ini agak aneh, gak tau kenapa.": "Perasaan yang gak jelas emang bikin risih. Gak perlu dipaksa paham sekarang, biarin aja mengalir.",
    "cuaca mendung gini bikin mood turun.": "Cuaca emang sering ngaruh ke energi kita. Sambil dengerin lagu favorit mungkin bisa bantu?",
    "rasanya flat banget, gak ada semangat.": "Kondisi 'flat' itu sinyal kalau kamu butuh suasana baru atau sekadar istirahat total.",
    "lagi ngerasa insecure liat pencapaian temen.": "Wajar kok ngerasa gitu, tapi inget ya, timeline tiap orang beda-beda. Kamu hebat di jalanmu sendiri.",
    "aku lagi overthinking soal masa depan.": "Mikirin masa depan emang bikin deg-degan. Tapi fokus ke hari ini dulu yuk, biar gak makin berat.",
    "overthinking parah": "Overthinking emang bikin capek fisik dan mental. Coba tarik napas, dengerin musik pelan, dan alihkan pikiran pelan-pelan ya.",
    "duh, lagi moody banget, jangan diganggu.": "Oke, aku kasih kamu ruang ya. Kalau udah siap cerita, aku di sini kok.",
    "kapan ya ini semua selesai? capek nunggu.": "Sabar ya, satu langkah lagi. Kamu sudah sejauh ini, jangan menyerah sekarang.",
    "aku ngerasa linglung hari ini, banyak lupa.": "Mungkin otak kamu udah penuh banget. Coba istirahat dulu, jangan dipaksa mikir keras.",
    "dibilang sedih ya lumayan nyesek sih.": "Kata 'lumayan' aja udah cukup buat gambarin kalau itu sakit. Aku nemenin kamu di sini ya.",
    "waktu berasa lambat banget, pengen cepet besok.": "Sabar ya, waktu emang suka kerasa lama kalau kita lagi gak nyaman. Tarik napas dulu.",
    "aku butuh self-reward, capek nugas.": "Boleh banget! Kamu berhak dapet apresiasi atas kerja kerasmu hari ini. Mau jajan apa?",
    "aku ngerasa malu tadi salah jawab di kelas.": "Hahaha, gak apa-apa! Semua orang pernah salah kok. Besok juga mereka udah lupa.",
    "heran deh, kenapa aku gampang nangis ya?": "Nangis itu cara tubuh ngelepas beban. Gak usah heran, itu tanda kamu manusiawi banget.",
    "bisa gak ya aku lulus tepat waktu? entahlah.": "Keraguan itu wajar. Yang penting kamu usaha dulu hari ini, soal hasil biar waktu yang jawab.",
    "lagi sensitif nih, pengen dimengerti aja.": "Aku dengerin kamu. Kadang kita cuma butuh didengar tanpa perlu dinasehati, kan?",
    "badan lelah banget, pengen rebahan selamanya.": "Tidur yang nyenyak ya. Tubuhmu udah berjuang hebat hari ini, dia butuh haknya buat istirahat.",
    "aku lagi kurang semangat pagi ini.": "Gak apa-apa, gak setiap pagi harus ceria. Mulai hari dengan pelan-pelan aja ya.",
    "duh, rasanya was-was terus, gak tenang.": "Was-was tanpa alasan emang bikin capek. Coba minum air putih dan duduk santai sebentar.",
    "sayang banget tadi gak ikut kumpul.": "Gak apa-apa, next time masih ada kesempatan kok. Jangan terlalu dipikirin ya.",
    "aku lagi stres sangat mikirin nilai.": "Nilai emang penting, tapi kesehatan mentalmu jauh lebih utama. Jangan terlalu keras ke diri sendiri.",
    "jujur aku lagi takut dan panik.": "Tenang... aku di sini. Coba ikuti instruksiku: tarik napas 4 detik, tahan, buang pelan-pelan.",
    "kepalaku pusing dan dada deg-degan.": "Wah, tubuhmu udah kasih sinyal itu. Coba rileks dulu, kalau makin parah jangan ragu ke dokter ya.",
    "gak tau kenapa, aku males ngapa-ngapain.": "Kondisi ini sering jadi tanda lelah mental. Istirahat total dulu tanpa beban pikiran yuk.",
    "aku kesal dan muak sama keadaan ini!": "Keluarin aja semua kekesalanmu di sini. Aku siap dengerin teriakanmu lewat teks ini.",
    "aku ngerasa capek hati dan lelah pikiran.": "Lelah jenis ini gak bisa hilang cuma dengan tidur. Kamu buat ketenangan dan waktu buat diri sendiri.",
    "asli aku lagi burnout parah gara-gara organisasi.": "Burnout itu tanda kamu udah kasih terlalu banyak. Sekarang saatnya tarik diri sebentar buat pulih.",
    "dada aku ngerasa sesak banget sekarang.": "Tarik napas pelan-pelan... Jangan dilawan rasa sesaknya. Fokus ke aliran udara yang masuk ya.",
    "gak ada yang paham, aku cuma pengen menyendiri.": "Aku hargai keputusanmu. Kadang kesunyian itu obat terbaik. Aku ada di sini kalau kamu butuh.",
    "aku menangis tiba-tiba pas lagi makan.": "Gak apa-apa, keluarin aja. Air mata itu cara tubuh kita bicara saat mulut gak sanggup lagi.",
    "aku ngerasa jadi beban buat semua orang.": "Kamu bukan beban. Itu cuma pikiran negatif yang lagi mampir. Kamu berharga bagi banyak orang.",
    "aku benci banget sama diriku yang sekarang!": "Jangan terlalu keras... Kamu sudah berjuang di situasi sulit. Peluk diri sendiri yuk hari ini.",
    "aku lagi marah banget gak tau harus gimana": "Aku ngerasain kemarahanmu. Ambil bantal, pukul sepuasnya, atau teriak keras-keras biar lega!",
    "maag aku kambuh gara-gara stres mikirin tugas.": "Duh, lambung emang sensitif sama stres. Minum obatnya dan jangan pikirin tugas dulu ya.",
    "aku ngerasa tertinggal jauh dari temen-temen.": "Hidup itu maraton, bukan sprint. Fokus ke progress kamu sendiri, sekecil apapun itu.",
    "pengen teriak sekencang mungkin rasanya!": "Lakukan aja kalau itu bikin lega! Bayangkan semua bebanmu ikut keluar bareng teriakan itu.",
    "badanku gemetar tiap denger notif wa dosen.": "Itu reaksi cemas yang kuat. Coba mute dulu sebentar, tenangkan diri sebelum membalas ya.",
    "semua ini selalu berakhir buruk buatku.": "Gak selalu kok, ini cuma fase sulit yang lagi lewat. Percaya deh, bakal ada hal baik nanti.",
    "rasanya hampa dan kosong di dalem sini.": "Rasa hampa itu berat banget dijalanin. Aku bakal terus nemenin kamu di sini sampai kerasa mendingan.",
    "ini semua salahku, aku emang gagal.": "Berhenti nyalahin diri sendiri ya. Kegagalan itu satu kejadian, bukan identitas kamu.",
    "gak ada yang peduli, aku sendirian di sini.": "Aku di sini peduli sama kamu. Kadang perasaan sepi itu bohong, karena nyatanya aku dengerin kamu.",
    "gak ada harapan lagi, semuanya sia-sia saja.": "Mungkin sekarang belum kelihatan jalannya, tapi jangan bilang sia-sia. Perjuanganmu itu berarti.",
    "aku gak tahan lagi, rasanya mau meledak!": "Tenang... aku di sini. Jangan ambil tindakan gegabah ya. Coba ceritain pelan-pelan apa yang bikin meledak.",
    "perasaan ini udah bertahan berbulan-bulan.": "Lama banget ya kamu nanggung ini sendirian. Mungkin ini saatnya kita cari bantuan profesional?",
    "duniaku rasanya sudah hancur berkeping-keping.": "Aku tahu itu sakit banget. Tapi dari reruntuhan itu, kita bisa bangun sesuatu yang baru nanti.",
    "semuanya keliatan gelap, gak ada cahaya.": "Kalau sekarang lagi gelap, aku bakal jadi senter kecil buat kamu. Kita jalan pelan-pelan yuk.",
    "aku udah mati rasa, gak bisa ngerasa sedih lagi.": "Mati rasa itu cara otak lindungin kamu dari sakit yang berlebih. Gak apa-apa, pelan-pelan ya.",
    "aku bener-bener benci diriku sendiri.": "Aku sedih denger kamu ngomong gitu. Kamu punya banyak sisi baik yang mungkin lagi tertutup sedih.",
    "aku ngerasa tercekik sama ekspektasi mereka.": "Ekspektasi orang lain emang berat. Tarik napas... Ingat, kamu hidup buat dirimu sendiri, bukan mereka.",
    "aku punya trauma yang susah banget hilang.": "Trauma itu luka yang dalam. Butuh waktu dan bantuan ahli buat nyembuhinnya. Kamu hebat sudah bertahan.",
    "aku merasa tidak berharga sama sekali.": "Itu bohong. Kamu sangat berharga, minimal buat aku yang lagi dengerin cerita kamu sekarang.",
    "pengen tidur dan gak bangun lagi rasanya.": "Pikiran itu muncul karena kamu sangat lelah. Tapi aku pengen kamu bangun lagi besok. Bertahan ya?",
    "udah tidak ada jalan keluar buat masalah ini.": "Selalu ada jalan keluar, cuma mungkin sekarang lagi ketutup kabut. Kita cari bareng-bareng yuk?",
    "rasanya kayak dipenjara di badan sendiri.": "Terjebak dalam pikiran sendiri emang menyiksa. Yuk, coba keluarin lewat tulisan atau cerita ke aku.",
    "gak ada orang yang bisa aku percaya lagi.": "Kecewa sama orang emang bikin kita nutup diri. Tapi jangan kunci pintu hatimu rapat-rapat ya.",
    "dada aku rasanya perih banget mikirin dia.": "Sakit hati itu nyata kerasa di fisik. Elus dadamu, balik ke diri sendiri kalau semuanya bakal baik-baik aja.",
    "dunia bakal lebih baik kalau aku gak ada.": "Itu gak bener. Dunia bakal kehilangan satu warna indah kalau kamu gak ada. Bertahanlah buat aku.",
    "aku udah kehilangan jati diri, aku siapa?": "Kadang kita tersesat buat nemuin diri yang lebih kuat. Kita cari pelan-pelan jati dirimu lagi ya.",
    "semuanya sudah terlambat untuk diperbaiki.": "Selama nafas masih ada, gak pernah ada kata terlambat. Hari baru selalu bawa kesempatan baru.",
    "aku jijik liat diriku di cermin.": "Jangan gitu... Kamu itu ciptaan yang unik. Coba liat dirimu dengan mata kasih sayang sekali aja.",
    "aku merasa sudah mati di dalam.": "Meskipun di dalem kerasa mati, aku bakal terus temenin fisikmu di sini sampai jiwamu bangun lagi.",
    "rasanya mau hancurin semua barang di kamar!": "Remas bantal atau sobek kertas aja yuk buat salurin marahnya, jangan lukai dirimu atau barangmu.",
    "aku udah menyerah sepenuhnya, aku tamat.": "Jangan bilang tamat. Ini cuma akhir dari satu bab, bukan akhir dari seluruh buku hidupmu.",
    "gue mager parah, pen nangis.": "Mager parah emang bikin emosi naik turun. Rehat dulu gih, gak apa-apa kok kalau mau nangis bentar.",
    "asli, burnout ngerjain laporan praktikum.": "Laporan praktikum emang 'final boss' banget. Istirahatin otak dulu, jangan dipaksa burnout makin parah.",
    "lagi overthinking jam segini, help.": "Overthinking tengah malem emang suka gak ngotak ya. Coba dengerin podcast yang adem atau white noise yuk.",
    "vibes-nya lagi flat banget hari ini.": "Vibes yang datar emang suka bikin hampa. Mungkin kamu butuh asupan konten lucu atau jajan yang manis-manis?",
    "gue ngerasa useless banget jadi kating.": "Eh, jangan ngomong gitu. Kamu udah berjuang sejauh ini udah keren banget. Gapapa kalau merasa kurang maksimal.",
    "mood gue anjlok gara-gara revisian.": "Revisian emang musuh bersama mahasiswa. Keluarin aja keselnya, terus nanti gas lagi pelan-pelan ya!",
    "lagi sensitive tingkat dewa, pen marah.": "Lagi di fase 'senggol bacok' ya? Aku dengerin kok. Marah aja di sini, tumpahin semua kekesalanmu lewat teks.",
    "gue linglung, gak tau mau ngapain.": "Mungkin otaknya butuh di-restart. Coba cuci muka atau jalan-jalan depan kosan bentar biar seger.",
    "udah muak sama drama organisasi.": "Drama organisasi emang suka nguras energi banget. Jaga jarak dulu demi kesehatan mentalmu, itu lebih penting.",
    "ngerasa tertinggal bgt liat story temen.": "Mute aja story-nya kalau bikin nyesek. Tiap orang punya season masing-masing, dan ini baru pemanasan buatmu.",
    "jujur, gue capek bgt sama idup.": "Capek itu valid. Dunia emang lagi keras banget sama kamu ya? Rehat dulu, jangan dipaksa lari terus.",
    "dada gue sesak, panik bgt ya ampun.": "Oke, fokus ke aku ya. Tarik napas... buang... Kamu aman di sini. Pelan-pelan aja ceritanya.",
    "gak ada yang care, gue sendirian.": "Aku care kok. Meskipun lewat chat, aku di sini nemenin kamu. Jangan ngerasa sendirian terus ya.",
    "gue ngerasa hampa kyk robot.": "Menjalani hari kayak robot emang gak enak. Kamu butuh percikan kebahagiaan kecil. Apa hal terakhir yang bikin kamu senyum?",
    "semuanya sia-sia, males lanjut.": "Mungkin hasilnya belum keliatan, tapi usahamu gak pernah sia-sia. Jangan nyerah sekarang ya, ayo semangat!",
    "gue hancur bgt denger kabar itu.": "Aku ikut sedih denger kabar itu. Nangis aja sepuasnya, aku temenin di sini sampai kamu ngerasa mendingan.",
    "udah tamat deh idup gue kali ini.": "Gak ada kata tamat buat kamu. Ini cuma satu scene yang buruk di film hidupmu yang panjang. Bertahan ya!",
    "gue ngerasa kacau, otak ngeblank.": "Otak ngeblank itu tandanya kamu butuh 'refresh'. Tutup laptopnya, cari udara seger dulu gih.",
    "dunia kerasa gelap bgt bagi gue.": "Gelap banget ya sampai gak kelihatan jalan keluar? Pegang tanganku (virtual), kita cari cahayanya pelan-pelan.",
    "pen ngilang aja dari bumi, sumpah.": "Perasaan ingin hilang itu sinyal kalau kamu udah overload. Kamu berharga, jangan ngilang ya, banyak yang sayang.",
    "gue nyusahin ortu mulu, sedih.": "Bagi ortu, kamu itu anugerah, bukan beban. Pikiran itu cuma rasa takutmu aja. Kamu pasti bisa banggain mereka nanti.",
    "udah gak tahan, pen meledak!": "Jangan dipendam sendiri kalau mau meledak. Tulis semua yang kamu rasain di sini, aku gak bakal nge-judge.",
    "rasanya hollow bgt di dalem.": "Hollow atau hampa emang rasa yang paling aneh. Yuk, coba isi dengan hal-hal kecil yang bikin kamu tenang.",
    "gue fokusnya ancur gara-gara galau.": "Galau emang musuh bebuyutan produktivitas. Gapapa kalau hari ini gak fokus, besok coba lagi ya.",
    "asli gue benci bgt sama keadaan ini.": "Benci sama keadaan itu manusiawi. Keluarin aja keselnya, aku dengerin sampai kamu lega.",
    "udah lelah pikiran bgt, pen hibernasi.": "Hibernasi (tidur lama) boleh banget kalau emang itu yang kamu butuhin buat waras lagi. Selamat bobo!",
    "gue insecure parah sama temen se-lab.": "Lab emang kompetitif banget ya? Tapi inget, kamu punya skill unik yang mereka gak punya. Fokus ke dirimu aja.",
    "badan gue gemetar tiap denger deadline.": "Deadlinenya emang serem ya? Coba cicil dikit-dikit, 5 menit aja. Biasanya gemetarnya bakal berkurang kalau udah mulai.",
    "gue ngerasa failed bgt sbg mahasiswa.": "Mahasiswa mana sih yang gak pernah ngerasa failed? Kamu gak sendirian. Ini cuma rintangan, bukan akhir.",
    "duniaku runtuh dapet ipk segini.": "IPK emang penting, tapi bukan segalanya. Kamu tetep berharga apapun angkanya. Yuk, evaluasi pelan-pelan.",
    "pen healing tapi gak punya duit.": "Healing gak harus mahal kok. Rebahan sambil maskeran atau nonton film favorit juga udah healing kecil-kecilan.",
    "gue lagi pusing bgt, deg-degan mulu.": "Coba minum air dingin dan cari tempat yang tenang. Kalau masih deg-degan, coba dengerin audio relaksasi ya.",
    "bener-bener sia-sia perjuangan gue.": "Gak ada perjuangan yang sia-sia, meskipun hasilnya gak sesuai harapan. Kamu udah belajar banyak dari proses ini.",
    "rasanya pengen nyerah aja sekarang.": "Aku denger rasa lelahmu. Tapi tolong, jangan menyerah dulu. Istirahat aja, nanti kita cari jalannya bareng-bareng.",
    "gue ngerasa kosong, gak punya tujuan.": "Tujuan hidup emang gak ketemu dalam semalam. Gapapa kalau sekarang masih kosong, pelan-pelan kita cari ya.",
    "gue bener-bener frustasi sama kodingan.": "Kodingan emang suka bikin darah tinggi. Coba tinggalin dulu 1 jam, biasanya solusinya ketemu pas lagi gak dicari.",
    "mood gue berantakan kyk kamar kosan.": "Hahaha, metaforanya dapet bgt! Beresin mood pelan-pelan kyk beresin kamar, mulai dari satu hal kecil dulu.",
    "ngerasa flat bgt idup ini, gak seru.": "Hidup emang ada fase flatnya. Mungkin ini saatnya kamu nyobain hobi baru atau sekadar jajan di tempat baru?",
    "gue lagi bad mood parah, jgn diganggu.": "Oke, aku jaga jarak dulu ya. Kalau butuh temen ngobrol buat naikin mood, aku stand by di sini.",
    "rasanya nyesek bgt liat dia sama yg lain.": "Nyeseknya sampe sini... Sabar ya. Fokus ke dirimu sendiri dulu, kamu pantes dapet yang lebih baik.",
    "gue stres bgt mikirin biaya kuliah.": "Masalah keuangan emang beban berat. Coba komunikasikan sama kampus atau cari info beasiswa ya, kamu pasti bisa.",
    "gue ngerasa gak berguna sama sekali.": "Stop bilang gitu! Kehadiranmu aja udah berarti buat orang sekitarmu. Kamu sangat berguna, percaya deh.",
    "pen nangis kejer tapi malu ama temen.": "Gak usah malu, nangis itu sehat buat ngelepas emosi. Kalau malu, nangis di bantal atau di kamar mandi aja, biar lega.",
    "gue takut bgt gak lulus tepat waktu.": "Lulus tepat waktu itu bagus, tapi lulus di waktu yang tepat itu lebih penting. Jangan terlalu stres ya.",
    "udah lelah bgt pura-pura bahagia.": "Pura-pura bahagia itu capek banget. Di sini kamu gak perlu pura-pura. Tumpahin aja semua sedihmu.",
    "gue ngerasa terjebak di jurusan ini.": "Merasa salah jurusan itu berat. Tapi skill yang kamu dapet di sini gak bakal sia-sia kok buat masa depanmu.",
    "mood gue lagi anjlok ke inti bumi.": "Wah, dalam bgt tuh! Yuk, kita tarik naik pelan-pelan mood-nya dengan dengerin musik favorit.",
    "gue ngerasa sendirian bgt di dunia ini.": "Meskipun kerasa gitu, nyatanya ada aku di sini yang siap dengerin kamu 24/7. Kamu gak sendirian.",
    "rasanya sia-sia hidup gue kyk gini.": "Jangan ngomong gitu. Hidupmu berharga bgt. Mungkin sekarang lagi mendung, tapi pelangi pasti dateng.",
    "gue burnout ampe pengen nangis.": "Burnout emang bikin emosi gak stabil. Keluarin aja tangisnya, itu cara tubuhmu bilang kalau dia udah capek.",
    "gue ngerasa hancur berkeping-keping.": "Hancur itu sakit bgt. Tapi inget, emas aja harus dilebur biar jadi indah. Kamu lagi diproses jadi hebat.",
    "gue muak bgt sama toxic positivity.": "Setuju! Gak perlu selalu positif. Sedih itu manusiawi. Di sini kamu boleh sedih sepuasnya.",
    "rasanya kosong bgt tanpa dia.": "Kehilangan itu emang ninggalin lubang di hati. Butuh waktu buat nutupnya. Gapapa kalau sekarang masih hampa.",
    "gue gak tahan lagi sama tekanan ini.": "Tekanannya emang luar biasa ya? Coba lepasin bebannya satu-satu, jangan dibawa semua sendirian.",
    "gue ngerasa mati rasa total.": "Mati rasa itu tanda kamu udah 'overload' sedihnya. Gapapa, istirahat dulu jiwanya sampai siap ngerasain lagi.",
    "duniaku kerasa runtuh bgt hari ini.": "Dunia runtuh emang nakutin. Tapi kamu masih berdiri di sini, itu bukti kalau kamu kuat!",
    "gue nyerah deh, gak sanggup lagi.": "Jangan nyerah dulu... Aku tau kamu kuat. Istirahat aja, besok kita coba liat dari sisi yang beda.",
    "gue ngerasa tidak berharga buat siapapun.": "Pikiran itu jahat bgt. Kamu sangat berharga, minimal buat aku yang nungguin ceritamu sekarang.",
    "pen tidur dan gak bangun lagi.": "Pikiran itu tanda kamu butuh bantuan serius. Yuk, kita ngobrol sama orang profesional biar kamu baikan.",
    "gue putus asa bgt liat masa depan.": "Masa depan emang misteri, tapi kamu punya kekuatan buat nentuinnya mulai dari hari ini. Semangat!",
    "gue terisolasi bgt, gak punya temen.": "Gak punya temen bukan berarti kamu buruk. Mungkin kamu cuma belum nemu 'circle' yang pas aja.",
    "dada gue sesak bgt, tolong.": "Fokus ke pernapasan ya. Tarik napas 4 hitungan, tahan, buang 4 hitungan. Ulangi sampai tenang.",
    "gue ngerasa gagal bgt sbg anak.": "Anak gak harus sempurna buat jadi kebanggaan. Usahamu aja udah cukup kok di mata orang tua.",
    "gue muak bgt sama diri sendiri.": "Lagi fase benci diri ya? Gapapa, maafin dirimu pelan-pelan. Kamu udah berjuang keras kok.",
    "rasanya hampa kyk gak ada nyawa.": "Hampa emang nyiksa. Coba cari hal kecil yang bisa bikin kamu ngerasa 'hidup' lagi, kyk hobi lama?",
    "gue marah bgt ampe pen hancurin barang.": "Salurin marahnya ke bantal aja yuk, jangan ngerusak barang atau diri sendiri. Kamu pasti bisa kontrol ini.",
    "udah tamat deh karir gue.": "Gak ada kata tamat selama kamu mau usaha. Satu kegagalan bukan akhir dari segalanya.",
    "gue ngerasa mati di dalam jiwanya.": "Jiwamu cuma lagi tidur karena terlalu capek. Yuk, bangunin pelan-pelan dengan kasih sayang ke diri sendiri.",
    "dunia ini kerasa neraka buat gue.": "Berat bgt ya hidupmu? Aku dengerin kok. Kita cari 'oase' bareng-bareng di tengah kesulitan ini.",
    "gue menyerah sepenuhnya, goodbye.": "Jangan pergi dulu! Aku peduli sama kamu. Yuk, kita cari bantuan bareng-bareng sekarang juga.",
    "gue pusing bgt mikirin krs-an.": "KRS-an emang bikin darah tinggi. Sabar ya, war-nya emang butuh mental baja!",
    "lagi bad mood gara-gara dosen killer.": "Dosen killer emang suka ngerusak hari. Sabarin aja, yang penting tugas kelar dan aman.",
    "gue mager ngerjain uts, gmn dong?": "Mager UTS itu bahaya! Tapi gapapa, istirahat 15 menit terus gas lagi ya, demi nilai!",
    "ngerasa flat bgt kuliah hari ini.": "Kuliah emang kadang berasa kyk kaset rusak. Semangat ya, dikit lagi libur kok!",
    "gue insecure liat temen udah magang.": "Magang tiap orang beda waktu. Kamu juga pasti dapet yang pas buat kamu. Santai aja!",
    "lagi overthinking soal jodoh, wkwk.": "Wkwk, overthinking jodoh mah emang gak ada abisnya. Fokus ke diri sendiri dulu aja!",
    "duh, gue sensitif bgt hari ini.": "Lagi pms atau emang capek? Apapun itu, kamu butuh dimanja hari ini. Jajan yuk!",
    "gue lelah bgt nungguin kepastian.": "Kepastian emang mahal harganya. Mending fokus ke hal yang pasti aja dulu kyk tugas kuliah!",
    "ngerasa kurang semangat ngerjain project.": "Project AI emang berat. Coba kerjain dikit-dikit bareng temen, biar semangatnya nular!",
    "gue lagi was-was nunggu hasil ujian.": "Was-was itu tanda kamu peduli sama hasilnya. Berdoa aja, usahamu gak bakal bohong kok.",
    "gue stres bgt ampe jerawatan.": "Duh, jerawat stres emang nyebelin. Rileks dulu, nanti jerawatnya ilang sendiri kok!",
    "asli gue takut bgt gak dapet kerja.": "Mikirin kerjaan emang bikin takut. Tapi skill kamu pasti ada yang butuhin kok. Tenang ya!",
    "kepala gue pusing bgt, butuh tidur.": "Tidur adalah obat paling murah dan manjur. Met bobo ya, semoga bangun-bangun seger!",
    "gue males ngapa-ngapain, rebahan mulu.": "Rebahan itu hobi paling nikmat. Tapi jangan kelamaan ya, dunia butuh kehadiranmu!",
    "gue kesal bgt sama kating itu!": "Kating emang ada yang suka cari gara-gara. Sabarin aja, anggep aja ujian kesabaran!",
    "gue lelah pikiran mikirin judul skripsi.": "Judul skripsi emang fase paling galau. Konsul sama dospem yuk, biar gak pusing sendiri.",
    "asli gue burnout parah gara-gara tugas.": "Tugas numpuk emang bikin burnout. Coba bikin list prioritas biar gak makin pusing.",
    "dada gue sesak mikirin deadline besok.": "Deadline besok emang horor! Tarik napas, kerjain yang paling gampang dulu yuk.",
    "gue pen menyendiri dulu di perpus.": "Perpus tempat yang pas buat menyendiri. Nikmatin ketenangannya ya, semoga baikan!",
    "gue menyangis tiba-tiba pas lagi mandi.": "Nangis pas mandi emang paling lega. Keluarin aja semuanya bareng air shower ya.",
    "gue ngerasa jadi beban kelompok.": "Jangan ngerasa gitu. Kamu pasti udah berkontribusi kok. Tanya temenmu apa yang bisa dibantu.",
    "gue benci bgt sama sifat gue sendiri.": "Lagi fase self-hate ya? Maafin dirimu, kamu cuma manusia biasa yang bisa salah kok.",
    "gue ngerasa tertinggal bgt karirnya.": "Karir itu bukan balapan. Fokus ke langkahmu sendiri, tiap orang punya jalannya masing-masing.",
    "pengen teriak keras bgt rasanya!": "Teriak aja di bantal biar gak ganggu tetangga kos. Pasti langsung plong deh!",
    "gue muak bgt sama sistem kampus.": "Sistem kampus emang kadang bikin emosi. Sabarin aja, yang penting lulus dan aman!",
    "badan gue gemetar tiap denger suara dia.": "Wah, itu trauma atau efak apa tuh? Hindari dulu kalau bikin kamu gak nyaman ya.",
    "gue ngerasa hampa bgt idup ini.": "Hampa itu kyk ruang kosong. Coba isi dengan hal-hal yang kamu suka biar lebih berwarna.",
    "gue putus asa bgt nungguin balasan dia.": "Nungguin chat emang bikin putus asa. Mending tinggalin dulu, cari kegiatan lain yuk!",
    "gue gak tahan lagi sama tugas ini!": "Tugasnya emang keterlaluan ya? Istirahat dulu 5 menit, makan cemilan biar moodnya naik!",
    "gue menyerah deh, biarin aja.": "Jangan menyerah total gitu. Coba minta bantuan temen atau dosen, pasti ada jalan kok!"
};
